# Build stage
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# Copy solution and projects
COPY ../CartonCaps.sln .
COPY ./CartonCaps/CartonCaps.csproj ./CartonCaps/
RUN dotnet restore CartonCaps/CartonCaps.csproj

# Copy the rest of the code
COPY ./CartonCaps/. ./CartonCaps/
WORKDIR /src/CartonCaps
RUN dotnet publish -c Release -o /app/publish

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

# Set environment to Development
ENV ASPNETCORE_ENVIRONMENT=Development

ENTRYPOINT ["dotnet", "CartonCaps.dll"]
